print("- Số nguyên (int)")
print("- Số thực (float)")
print("- Số phức (complex)")
print("- Chuỗi ký tự (str)")
print("- Boolean (bool)")
print("- Danh sách (list)")
print("- Tuple (tuple)")
print("- Tập hợp (set)")
print("- Từ điển (dict)")